image: 'maven:3.5.0-jdk-8'
stages:
    - build
    - deploy
variables:
    CI_REPOSITORY_URL: 'http://${LDAP_USER}:${LDAP_PASS}@gitlab.sysmo.com.br/${CI_PROJECT_PATH}.git'
    GIT_SUBMODULE_STRATEGY: recursive
    GIT_STRATEGY: clone
    MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end -Dmaven.wagon.http.retryhandler.class=standard -Dmaven.wagon.http.retryHandler.count=3 -DinstallAtEnd=true -DdeployAtEnd=true -Duser.timezone=America/Sao_Paulo -Duser.language=pt -Duser.region=BR -Duser.country=BR "
    MAVEN_OPTS: "-Dmaven.repo.local=$HOME/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true -Dorg.slf4j.simpleLogger.defaultLogLevel=WARN"
    CURL_OPTS: "--retry 3 --retry-delay 10"
before_script:
    - 'git config --global user.email "gitlab-ci@sysmo.com.br"'
    - 'git config --global user.name "Gitlab-CI"'   
    - 'echo "<settings><servers><server><id>maven-releases</id><username>${LDAP_USER}</username><password>${LDAP_PASS}</password></server><server><id>gitlab</id><username>${LDAP_USER}</username><password>${LDAP_PASS}</password></server></servers><mirrors><mirror><id>maven-releases</id><mirrorOf>*</mirrorOf><url>${NEXUS_URL}</url></mirror></mirrors><profiles><profile><id>sonar</id><activation><activeByDefault>true</activeByDefault></activation><properties><sonar.host.url>${SONAR_URL}</sonar.host.url><sonar.login>${LDAP_USER}</sonar.login><sonar.password>${LDAP_PASS}</sonar.password></properties></profile></profiles></settings>" > $HOME/.m2/settings.xml'
compile:
    stage: build
    only:
        - develop
        - /^release.*$/
        - /^hotfix.*$/
    when: manual
    script:
        - 'mvn $MAVEN_CLI_OPTS versions:set -DremoveSnapshot'
        - 'mvn $MAVEN_CLI_OPTS clean compile -Pproduction -Dmaven.test.skip=true'
deploy:
    stage: deploy
    only:
        - develop
        - /^release.*$/
        - /^hotfix.*$/
    #when: manual
    script:
        - 'git checkout -B "${CI_BUILD_REF_NAME}"'
        - 'mvn $MAVEN_CLI_OPTS versions:set -DremoveSnapshot'
        - 'VRS_RELEASE=$(mvn -q -Dexec.executable=echo -Dexec.args=''${project.version}'' --non-recursive exec:exec)'
        - 'mvn $MAVEN_CLI_OPTS deploy -Dmaven.test.skip=true'
        - 'git tag -a ${VRS_RELEASE} -m "Doc: new tag from ${CI_BUILD_REF_NAME}"'
        - 'git push --follow-tags $CI_REPOSITORY_URL'
        - 'curl $CURL_OPTS -sS -X POST -F "token=${PRJ_DEPENDENCIES_TOKEN}" -F "ref=${CI_BUILD_REF_NAME}" -F "variables[PROJETO]=s1.server.dto.version" -F "variables[NEW_VERSION]=${VRS_RELEASE}" http://gitlab.sysmo.com.br/api/v3/projects/${PRJ_DEPENDENCIES_ID}/trigger/builds'
        - 'git reset --hard'
        - 'VRS_MIN=${VRS_RELEASE##*[!0-9]}'
        - 'VRS_MAJ=${VRS_RELEASE%%$VRS_MIN}'
        - 'VRS_NVERS=${VRS_MAJ}$((VRS_MIN+1))'
        - 'VRS_SNAPSHOT=${VRS_NVERS}-SNAPSHOT'
        - 'mvn $MAVEN_CLI_OPTS versions:set -DnewVersion=${VRS_SNAPSHOT}'
        - 'git commit -a -m "Doc: Next version ${VRS_SNAPSHOT}"'
        - 'git push $CI_REPOSITORY_URL'